### ISSUE TITLE
Command 'Settings Organizer: Global' resulted in an error

### ISSUE THREAD

**Issue by SuperBartimus** [HYP3R00T/settings-organizer#1]
Command 'Settings Organizer: Global' resulted in an error
Expected double-quoted property name in JSON at position 9549 (line 418 column 6)

Received above error when trying to initiate the global command.

Running Visual Studio Code Version: 1.91.1
Microsoft Windows 11 Enterprise 22631 (23h2)

**Comment by HYP3R00T** [comment]
Thanks for reporting the issue. 

This issue is called because the `settings.json` file might contain a comment line (which a normal JSON file doesn't allow) or at the very last line, we have a comma at the end which makes the parser think there would be another key-value pair.

I am working on this issue. 

Temp Solution:
- Remove all comments
- Remove `,` (comma) after the last key-value pair

**Comment by HYP3R00T** [comment]
The issue is not fixed. Kindly update the extension to v0.0.13

**Comment by HYP3R00T** [comment]
Issue is closed.
