### ISSUE TITLE
// 造成的问题

### ISSUE THREAD

**Issue by DontBeAlarmed** [HYP3R00T/settings-organizer#2]
The comments are cleared after use, and an error is reported if // is present in the value.
 "http.proxy": "http://127.0.0.1:1087",

**Comment by HYP3R00T** [comment]
Thanks for raising the issue. I am sorry that you lost your comments because of the extension. I am looking into the issue and will fix it. 

As I understand, you want the inline comment to stay at the end of the key-value pair. Do you have any preference for the block comment? I don't think block comments makes sense as it will rearrange everything. Is it alright if it removes the block comment altogether? Or shall I make it push to the end of the file? 

Sample `settings.json`
```json
{
    "[python]": {
        "diffEditor.ignoreTrimWhitespace": false, // This is an inline comment
        // This is a block comment
        "editor.wordBasedSuggestions": "off"
    }
}
```

**Comment by HYP3R00T** [comment]
This is now fixed. Closing the issue.
